[theme]
primaryColor = "#212121"   # Color for buttons and interactive elements
backgroundColor = "#212121"  # Page background color
secondaryBackgroundColor = "#171717"  # Sidebar and secondary areas
textColor = "#ebebeb"  # Default text color
font = "sans serif"  # Available options: 'serif', 'sans serif', 'monospace'